version: '3'

services: 
  dragonstackdb:
    image: postgres:14-alpine
    container_name: dragonstackdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backend/sql/account.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/sql/generation.sql:/docker-entrypoint-initdb.d/2.sql
      - ./backend/sql/dragon.sql:/docker-entrypoint-initdb.d/3.sql
      - ./backend/sql/trait.sql:/docker-entrypoint-initdb.d/4.sql
      - ./backend/sql/dragonTrait.sql:/docker-entrypoint-initdb.d/5.sql
      - ./backend/sql/accountDragon.sql:/docker-entrypoint-initdb.d/6.sql
    ports:
      - '5432:5432'
    restart: on-failure:10
    environment:
      POSTGRES_DB: dragonstackdb
      POSTGRES_USER: d_user
      POSTGRES_PASSWORD: d_pass
      # TZ: 'UTC+1'
      # PGTZ: 'UTC+1'

networks:
  default:
    name: dragonsnet
    